=== TrueIchiro/SS4/XML4UE/XML4_UE01_Niedermayr/Beispiel 1.6/kontakte5.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Lisa Niedermayr (S1710458025)
Abgabedatum: 13.03.2019
Beispiel 1.6
-->
<!ENTITY countries SYSTEM "kontakte5_countries.xml">

<!ELEMENT contactList (countries*, contacts*)>

<!-- Countries -->
<!ELEMENT countries (Country*)>

<!ELEMENT Country (#PCDATA | CountryTelephoneCode)*>
<!ATTLIST Country Code ID #REQUIRED>
<!ELEMENT CountryTelephoneCode (#PCDATA)>

<!-- contacts -->
<!ELEMENT contacts (contact*)>

<!ELEMENT contact (contactInfo, internetInfo, phoneNumbers, adresses)>
<!ATTLIST contact id ID #REQUIRED>

<!-- contactInfo -->
<!ELEMENT contactInfo (fullName, company?, jobTitle?, fileAs?)>

<!ELEMENT fullName (title?, firstName?, middleName?, lastName, suffix?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT middleName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT suffix (#PCDATA)>

<!ELEMENT company (#PCDATA)>
<!ELEMENT jobTitle (#PCDATA)>
<!ELEMENT fileAs (#PCDATA)>

<!-- internetInfo -->
<!ELEMENT internetInfo (email, displayAs?, webPageAddress?, imAdress?)>

<!ELEMENT email (#PCDATA)>
<!ELEMENT displayAs (#PCDATA)>
<!ELEMENT webPageAddress (#PCDATA)>
<!ELEMENT imAdress (#PCDATA)>

<!-- phoneNumbers -->
<!ELEMENT phoneNumbers (number*)>

<!ELEMENT number (#PCDATA)>
<!ATTLIST number type (business | home | fax | mobile) #REQUIRED>

<!-- adresses -->
<!ELEMENT adresses (business?)>
<!ELEMENT business (street?, city?, stateOrProvince?, zipOrPostalCode?)>

<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT stateOrProvince (#PCDATA)>
<!ELEMENT zipOrPostalCode (#PCDATA)>
<!ATTLIST business countryOrRegion IDREFS #IMPLIED>

=== TrueIchiro/SS4/XML4UE/XML4_UE01_Niedermayr/Beispiel 1.6/contacts5.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE contactList SYSTEM "kontakte5.dtd">
<!--
Lisa Niedermayr (S1710458025)
Abgabedatum: 13.03.2019
Beispiel 1.6
-->
<contactList>
	&countries;
	<contacts>
		<contact id="cId_1337">
			<contactInfo>
				<fullName>
					<title>Mr.</title>
					<firstName>Nicolas</firstName>
					<middleName>Nic</middleName>
					<lastName>Gangsta</lastName>
					<suffix>-zen</suffix>
				</fullName>
				<company>Benriya</company>
				<jobTitle>Cleaner</jobTitle>
				<fileAs>Gangsta, Nicolas</fileAs>
			</contactInfo>
			<internetInfo>
				<email>nic_no_care@none.gg</email>
				<displayAs>Nic (nic_no_care@none.gg)</displayAs>
				<webPageAddress>www.benriya.gg</webPageAddress>
				<imAdress>SilentNic</imAdress>
			</internetInfo>
			<phoneNumbers>
				<number type="business">0045 2945</number>
				<number type="home">0422 7738</number>
				<number type="fax">0066 7324</number>
				<number type="mobile">0666 1337</number>
			</phoneNumbers>
			<adresses>
				<business countryOrRegion="AUT">
					<street>Northern Ring 445</street>
					<city>Ergastulum</city>
					<stateOrProvince>Northern Gate</stateOrProvince>
					<zipOrPostalCode>9990</zipOrPostalCode>
				</business>
			</adresses>
		</contact>
		<contact id="cId_22">
			<contactInfo>
				<fullName>
					<firstName>PenPen</firstName>
					<lastName>Pyo</lastName>
				</fullName>
				<company>The World</company>
				<jobTitle>Professional Penguin</jobTitle>
				<fileAs>Pyo, PenPen</fileAs>
			</contactInfo>
			<internetInfo>
				<email>pen2@pyo-pyo.pui</email>
				<displayAs>PenyPeny</displayAs>
				<imAdress>PenToPen</imAdress>
			</internetInfo>
			<phoneNumbers>
				<number type="business">4855 2234</number>
				<number type="fax">+0224 4234</number>
			</phoneNumbers>
			<adresses>
				<business countryOrRegion="GBR">
					<city>Neo Tokyo</city>
					<zipOrPostalCode>0000</zipOrPostalCode>
				</business>
			</adresses>
		</contact>
		<contact id="cId_969">
			<contactInfo>
				<fullName>
					<title>Mrs.</title>
					<firstName>Catherine</firstName>
					<middleName>Amaltia</middleName>
					<lastName>Roy</lastName>
				</fullName>
				<company>IUSA</company>
				<jobTitle>Engineer</jobTitle>
				<fileAs>Cath</fileAs>
			</contactInfo>
			<internetInfo>
				<email>cath_is_cool_lel@yoyo.po</email>
				<displayAs>Cath@Roy</displayAs>
				<webPageAddress>www.iusa.org/catherine</webPageAddress>
				<imAdress>Cathastrophic</imAdress>
			</internetInfo>
			<phoneNumbers>
				<number type="business">7377 2895</number>
				<number type="fax">9843 8405</number>
				<number type="mobile">7315 4395</number>
			</phoneNumbers>
			<adresses>
				<business countryOrRegion="SUI">
					<street>Quarter 447</street>
					<city>Otario</city>
					<zipOrPostalCode>572387</zipOrPostalCode>
				</business>
			</adresses>
		</contact>
	</contacts>
</contactList>
