=== TrueIchiro/SS4/XML4UE/XML4_UE04_Niedermayr/ue04_contacts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- based on juergens work -->
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:fhhgb="http://www.fh-hagenberg.at/contacts" 
	targetNamespace="http://www.fh-hagenberg.at/contacts" 
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation xml:lang="DE">
			2012-04-23		XML Uebung 03
			a.heinzel, w.strasser 
			based on juergens work
		</xs:documentation>
	</xs:annotation>
	<xs:element name="contactList" type="fhhgb:contactListType">
		<xs:key name="countryCodeKey">
			<xs:selector xpath="fhhgb:countries/fhhgb:country"/>
			<xs:field xpath="@code"/>
		</xs:key>
		<xs:keyref name="countryCodeKeyRef" refer="fhhgb:countryCodeKey">
			<xs:selector xpath="fhhgb:contacts/fhhgb:contactEntry/fhhgb:address/fhhgb:country"/>
			<xs:field xpath="@code"/>
		</xs:keyref>
		<xs:unique name="contactIdUnique">
			<xs:selector xpath="fhhgb:contacts/fhhgb:contactEntry"/>
			<xs:field xpath="@id"/>
		</xs:unique>
	</xs:element>
	<xs:simpleType name="countryCodeType">
		<xs:restriction base="xs:string">
			<xs:minLength value="3"/>
			<xs:maxLength value="3"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="phoneAttrType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="business"/>
			<xs:enumeration value="private"/>
			<xs:enumeration value="fax"/>
			<xs:enumeration value="mobile"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="salutationType">
		<xs:annotation>
			<xs:documentation>
				Based on the screenshot it is impossible to tell if the user 
				is allowed to also enter custom values for this field.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Mr"/>
			<xs:enumeration value="Mrs"/>
			<xs:enumeration value="Dr"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="nameAffixType">
		<xs:annotation>
			<xs:documentation>
				Based on the screenshot it is impossible to tell if the user 
				is allowed to also enter custom values for this field.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="I"/>
			<xs:enumeration value="II"/>
			<xs:enumeration value="III"/>
			<xs:enumeration value="Jr."/>
			<xs:enumeration value="Sr."/>
			<xs:enumeration value="BSc"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="zipCodeType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="1000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="emailAddressType">
		<xs:restriction base="xs:string">
			<xs:pattern value=".+@.+\..+"/>
			<!-- could be more specific, but it at least asserts that there is an @ and something which looks like an domain -->
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="countryTelephoneCodeType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[+]{1}[0-9]{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="contactListType">
		<xs:sequence>
			<xs:element name="countries" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="country" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="name" type="xs:string"/>
									<xs:element name="telephoneCode" type="fhhgb:countryTelephoneCodeType"/>
								</xs:sequence>
								<xs:attribute name="code" type="fhhgb:countryCodeType" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="contacts" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="contactEntry" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="contact">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="person">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="salutation" type="fhhgb:salutationType" minOccurs="0"/>
															<xs:element name="firstName" type="xs:string" minOccurs="0"/>
															<xs:element name="middleName" type="xs:string" minOccurs="0"/>
															<xs:element name="lastName" type="xs:string"/>
															<xs:element name="nameAffix" type="fhhgb:nameAffixType" minOccurs="0"/>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element name="company" type="xs:string" minOccurs="0"/>
												<xs:element name="position" type="xs:string" minOccurs="0"/>
												<xs:element name="fileAs" type="xs:string" minOccurs="0">
													<xs:annotation>
														<xs:documentation>
															Based on the screenshot it is impossible to tell if the user 
															is allowed to also enter custom values for this field.
														</xs:documentation>
													</xs:annotation>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									<xs:element name="internet" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="eMail" type="fhhgb:emailAddressType" maxOccurs="3"/>
												<xs:element name="displayAs" type="xs:string" minOccurs="0"/>
												<xs:element name="website" type="xs:string" minOccurs="0"/>
												<xs:element name="imAddress" type="xs:string" minOccurs="0"/>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									<xs:element name="phone" minOccurs="0" maxOccurs="4">
										<xs:complexType>
											<xs:simpleContent>
												<xs:extension base="xs:string">
													<xs:attribute name="type" type="fhhgb:phoneAttrType" use="required"/>
												</xs:extension>
											</xs:simpleContent>
										</xs:complexType>
									</xs:element>
									<xs:element name="address" maxOccurs="1">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="street" type="xs:string"/>
												<xs:element name="place" type="xs:string"/>
												<xs:element name="state" type="xs:string"/>
												<xs:element name="zipCode" type="fhhgb:zipCodeType"/>
												<xs:element name="country">
													<xs:complexType>
														<xs:attribute name="code" type="xs:string" use="required"/>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
											<xs:attribute name="type" use="required">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:enumeration value="business"/>
														<xs:enumeration value="private"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
											<xs:attribute name="mailingAddress" type="xs:boolean" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="id" type="xs:int" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== TrueIchiro/SS4/XML4UE/XML4_UE04_Niedermayr/ue04_contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- based on juergens work -->
<fhhgb:contactList 
	xsi:schemaLocation="http://www.fh-hagenberg.at/contacts ue04_contacts.xsd" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:fhhgb="http://www.fh-hagenberg.at/contacts"
	xmlns="http://www.fh-hagenberg.at/contacts"
	>	
	<countries>
		<country code="AUT">
			<name>Österreich</name>
			<telephoneCode>+43</telephoneCode>
		</country>
		<country code="DEU">
			<name>Deutschland</name>
			<telephoneCode>+49</telephoneCode>
		</country>
		<country code="SUI">
			<name>Schweiz</name>
			<telephoneCode>+41</telephoneCode>
		</country>
		<country code="GBR">
			<name>Großbritannien</name>
			<telephoneCode>+44</telephoneCode>
		</country>
	</countries>
	<contacts>
		<contactEntry id="1">
			<contact>
				<person>
					<salutation>Mr</salutation>
					<firstName>Wolfgang</firstName>
					<lastName>Strasser</lastName>
				</person>
				<company>FH-OOE</company>
			</contact>
			<internet>
				<eMail>wolfgang.strasser@fh-hagenberg.at</eMail>
				<website>www.fh-ooe.at</website>
			</internet>
			<phone type="business">0660/123456789</phone>
			<address type="business" mailingAddress="true">
				<street>Haidfeldstrasse 33</street>
				<place>Leonding</place>
				<state>OOE</state>
				<zipCode>4060</zipCode>
				<country code="AUT"/>
			</address>
		</contactEntry>
		<contactEntry id="2">
			<contact>
				<person>
					<salutation>Mr</salutation>
					<firstName>Andreas</firstName>
					<lastName>Heinzel</lastName>
				</person>
				<company>FH-OOE</company>
			</contact>
			<internet>
				<eMail>wolfgang.strasser@fh-hagenberg.at</eMail>
				<website>www.fh-ooe.at</website>
			</internet>
			<phone type="mobile">0664/978654321</phone>
			<address type="private" mailingAddress="false">
				<street>Mustermannstrasze. 1</street>
				<place>Musterdorf</place>
				<state>OOE</state>
				<zipCode>5643</zipCode>
				<country code="AUT"/>
			</address>
		</contactEntry>
		<contactEntry id="3">
			<contact>
				<person>
					<salutation>Mrs</salutation>
					<firstName>Mona</firstName>
					<middleName>Ana</middleName>
					<lastName>Mustermann</lastName>
				</person>
				<company>FH-OOE</company>
			</contact>
			<internet>
				<eMail>mona.mustermann@fh-hagenberg.at</eMail>
				<website>www.mustermann.at</website>
			</internet>
			<phone type="private">0664/1111444422</phone>
			<address type="business" mailingAddress="true">
				<street>Musterweg 47a</street>
				<place>Musterstadt</place>
				<state>BERN</state>
				<zipCode>1236</zipCode>
				<country code="SUI"/>
			</address>
		</contactEntry>
	</contacts>
</fhhgb:contactList>
